export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SINGLE_RECIPE_START = 'SINGLE_RECIPE_START';
export const SINGLE_RECIPE_SUCCESS = 'SINGLE_RECIPE_SUCCESS';
export const SINGLE_RECIPE_FAIL = 'SINGLE_RECIPE_FAIL';